<?php

    // SE DECLARA CONSTANTE DE Vehiculos CADA VEZ QUE NOMBREMOS "CONTROLADOR_PRINCIPAL
    define("CONTROLADOR_PRINCIPAL", "Vehiculos");

    // ACCIÓN PREDEFINIDA
    define("ACCION_PRINCIPAL", "index");




?>